### PR TITLE
russian translation and add missing quotation marks (')

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by Blueberryy** [comment]
Didn't tested yet, might need some corrections.

**Comment by Blueberryy** [comment]
Ah, font for subtitles doesn't support Russian glyphs. @That1M8Head you or someone will have to add more glyphs for font

**Comment by AeriaVelocity** [comment]
I know 0% Russian so this isn't something I could do, I'm afraid

I could just remove the custom font and stick with the built-in ZDoom fonts, though

**Comment by Blueberryy** [comment]
Well you can look at GZDoom fonts or just take a look how generic russian characters look

**Comment by Blueberryy** [comment]
> Well you can look at GZDoom fonts or just take a look how generic russian characters look

i will review your work if you will need

**Comment by AeriaVelocity** [comment]
I'm just gonna revert to the regular ZDoom font, I'll look into replacing the fonts again sometime in the future, but this'll work for now

**Comment by Blueberryy** [comment]
Kind of bad to remove this font at all. I think it would be better to just *disable* strings in translated language file that used in places with mod's font until i figure out how to open font files and add new

**Comment by AeriaVelocity** [comment]
It's not a huge deal, and not all the fonts were replaced anyway

Plus, when I eventually get the confidence to make my own font that works properly, that'll be better than what I had before, so I'm fine with leaving it without a custom font for now

**Pull request closed without merging**
